# coding: utf-8

"""
    TagAPI

    API for the tags microservice of laWiki web appplication. It provides all endpoints related to CRUD operatios for wiki tags.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.v1_editors_api import router as V1EditorsApiRouter
from openapi_server.apis.v1_public_api import router as V1PublicApiRouter
from openapi_server.apis.v2_editors_api import router as V2EditorsApiRouter
from openapi_server.apis.v2_internal_api import router as V2InternalApiRouter
from openapi_server.apis.v2_public_api import router as V2PublicApiRouter

app = FastAPI(
    title="TagAPI",
    description="API for the tags microservice of laWiki web application. It provides all endpoints related to CRUD operatios for wiki tags.",
    version="2.0",
)

app.include_router(V1EditorsApiRouter)
app.include_router(V1PublicApiRouter)
app.include_router(V2EditorsApiRouter)
app.include_router(V2InternalApiRouter)
app.include_router(V2PublicApiRouter)
