# coding: utf-8

"""
    CommentsAPI

    API for the Comments microservice of laWiki web appplication. It provides all endpoints related to CRUD operatios for articles comments.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter
from openapi_server.apis.internal_api import router as InternalApiRouter

app = FastAPI(
    title="CommentsAPI",
    description="API for the Comments microservice of laWiki web appplication. It provides all endpoints related to CRUD operatios for articles comments.",
    version="1.0",
)

app.include_router(DefaultApiRouter)
app.include_router(InternalApiRouter)
