# coding: utf-8

"""
    laWiki API Gateway

    The Articles API provides endpoints for managing and retrieving articles and article versions within the wiki application. It supports core CRUD (Create, Read, Update, Delete) operations, search functionality, and versioning.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from openapi_server.apis.v1_admins_api import router as V1AdminsApiRouter
from openapi_server.apis.v1_editors_api import router as V1EditorsApiRouter
from openapi_server.apis.v1_public_api import router as V1PublicApiRouter

app = FastAPI(
    title="laWiki API Gateway",
    description="The Articles API provides endpoints for managing and retrieving articles and article versions within the wiki application. It supports core CRUD (Create, Read, Update, Delete) operations, search functionality, and versioning.",
    version="1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(V1AdminsApiRouter)
app.include_router(V1EditorsApiRouter)
app.include_router(V1PublicApiRouter)
