# coding: utf-8

"""
    CommentsAPI

    API for the Comments microservice of laWiki web appplication. It provides all endpoints related to CRUD operatios for articles comments.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.v1.v1_internal_api import router as V1InternalApiRouter
from openapi_server.apis.v1.v1_public_api import router as V1PublicApiRouter
from openapi_server.apis.v2.v2_internal_api import router as V2InternalApiRouter
from openapi_server.apis.v2.v2_public_api import router as V2PublicApiRouter

app = FastAPI(
    title="CommentsAPI",
    description="API for the Comments microservice of laWiki web appplication. It provides all endpoints related to CRUD operatios for articles comments.",
    version="2.0",
)

app.include_router(V1InternalApiRouter)
app.include_router(V1PublicApiRouter)
app.include_router(V2InternalApiRouter)
app.include_router(V2PublicApiRouter)
