# coding: utf-8

"""
    Ratings

    lawiki Ratings Api

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Ratings",
    description="lawiki Ratings Api",
    version="0.1",
)

app.include_router(DefaultApiRouter)
