services:
  api_gateway:
    container_name: api_gateway
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 3000

  comments:
    container_name: comments_api
    build:
      context: ./microservices/comments
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

  articles:
    container_name: articles_api
    build:
      context: ./microservices/articles
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8081

  ratings:
    container_name: ratings_api
    build:
      context: ./microservices/ratings
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8082

  tags:
    container_name: tags_api
    build:
      context: ./microservices/tags
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8083

  wikis:
    container_name: wikis_api
    build:
      context: ./microservices/wikis
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./config.env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8084

  libretranslate:
    container_name: libretranslate
    build:
      context: ./microservices/libre_translate
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,es,fr
